# name: CI/CD with GHCR, Docker Hub, and ArgoCD

# on:
#   push:
#     branches:
#       - develop
#       - main

# jobs:
#   # -------------------
#   # 1. CI: Build & Push Images
#   # -------------------
#   build-and-push:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write # For GHCR
#     steps:
#       # Checkout source code
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Log in to GHCR
#       - name: Log in to GHCR
#         uses: docker/login-action@v2
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       # Log in to Docker Hub
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       # Build and push frontend
#       - name: Build and push frontend
#         uses: docker/build-push-action@v4
#         with:
#           context: ./frontend
#           push: true
#           tags: |
#             ghcr.io/${{ github.repository_owner }}/atos-digital-academy-fe:1.${{ github.run_number }}.${{ github.sha }}
#             ghcr.io/${{ github.repository_owner }}/atos-digital-academy-fe:latest
#             ${{ secrets.DOCKERHUB_USERNAME }}/atos-digital-academy-fe:1.${{ github.run_number }}.${{ github.sha }}
#             ${{ secrets.DOCKERHUB_USERNAME }}/atos-digital-academy-fe:latest

      # Build and push backend
      # - name: Build and push backend
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./backend
      #     push: true
      #     tags: |
      #       ghcr.io/${{ github.repository_owner }}/atos-digital-academy-be:1.${{ github.run_number }}.${{ github.sha }}
      #       ghcr.io/${{ github.repository_owner }}/atos-digital-academy-be:latest
      #       ${{ secrets.DOCKERHUB_USERNAME }}/atos-digital-academy-be:1.${{ github.run_number }}.${{ github.sha }}
      #       ${{ secrets.DOCKERHUB_USERNAME }}/atos-digital-academy-be:latest

  # -------------------
  # 2. CD: Update GitOps repo for ArgoCD
  # -------------------
  # deploy:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Checkout GitOps repo
  #     - name: Checkout GitOps repo
  #       uses: actions/checkout@v3
  #       with:
  #         repository: Cypher1305/helm-dev
  #         token: ${{ secrets.GITOPS_PAT }} # Personal Access Token with repo access

  #     # Update image tags in Kubernetes manifests
  #     - name: Update manifests
  #       run: |
  #         sed -i "s|ghcr.io/.*/atos-digital-academy-fe:.*|ghcr.io/${{ github.repository_owner }}/atos-digital-academy-fe:1.${{ github.run_number }}.${{ github.sha }}|" helm/application_ada-fe.yaml
  #         sed -i "s|ghcr.io/.*/atos-digital-academy-be:.*|ghcr.io/${{ github.repository_owner }}/atos-digital-academy-be:1.${{ github.run_number }}.${{ github.sha }}|" helm/application_ada-be.yaml

  #     # Commit and push changes
  #     - name: Commit and push
  #       run: |
  #         git config user.name "github-actions"
  #         git config user.email "actions@github.com"
  #         git add helm/
  #         git commit -m "Update images to ${{ github.sha }}"
  #         git push
